### ISSUE TITLE
Unable to locate the output file!

### ISSUE THREAD

**Issue by ArmanKabiri** [LuminosoInsight/wikiparsec#9]
Hi. I'm trying to parse enWiktionary dump using "wiktionary-parser". However, after the execution is done, nothing is created as the output file, or at least I cannot find it.

**Comment by ArmanKabiri** [comment]
I got it. The program does not save the output into a file, but shows all results on the console screen. You can just add ">filename.json" to the end of the command to have it write the result into the file.

**Comment by rspeer** [comment]
This is a good point: the instructions didn't describe where the output goes at all. I've fixed the README. Thanks.
